Feature order #29
tamagocchi/nagano_cake pull request #41
Opened 2021-04-22 02:25 UTC by Taka2401

注文確定時の機能まで。注文履歴一覧と注文履歴詳細は作成中。

2021-04-22 02:30 UTC, mi-1109 approved these changes
ありがとうございます！
テスト設計書見ながら確認しちゃうので、コードは細かく見てませんが、一旦マージお願いします：）
何かあればご連絡しますね。

2021-04-22 02:31 UTC, uran556 approved these changes
ありがとうございます！

2021-04-24 09:13 UTC, uran556 approved these changes
ありがとうございます！
確認しました！

2021-04-24 09:25 UTC, mi-1109 requested changes
1.以下のファイルに <<<<HEADがついてるので、消していただけますか？
マージ後に自動的に消えるものであれば、お見捨ておきください。
application.scss
order_details_controller
orders_controller
addresses/index.html
schema.rb: 

2. schema.rb:
customersテーブルですが、is_deletedのdefaultとnullの値が消えてしまっているので、お手数ですが、rails generate migration ChangeIsDeletedDefaultOnCustomerでmigrationファイル作成して、以下の通り記述の上、rails db:migrateしてから再プッシュしていただけるでしょうか。ここが設定されていないと、退会機能がうまく機能しないので・・・＞＜
class ChangeIsDeletedDefaultOnCustomer < ActiveRecord::Migration[5.2]
  def up
    change_column :customers, :is_deleted, :boolean, default: false, null: false
  end
end

3. orders.scss: 25行目にコメントアウトされているHeightを削除

4. addresses_controller.rb: @address.customer_id = 1になっているんですが、これだとID＝1のcustomerしか登録できなくならないでしょうか・・・？削除してしまっても大丈夫かと思います！

2021-04-24 13:35 UTC, merged